(()=>{
'use strict';
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),digits=v=>String(v||'').replace(/\D/g,''),active=t=>!(t?.cancelled||t?.cancelChecked===true),db=()=>window.db&&Array.isArray(window.db.sales)?window.db:null;
function pax(s){if(s?.passengers?.length)return s.passengers.length;let n=['adults','children','babies','seniors','free'].reduce((a,k)=>a+Number(s?.[k]||0),0);if(n)return n;return Math.max(0,...(s?.tours||[]).filter(active).map(t=>['adults','children','babies','seniors','free'].reduce((a,k)=>a+Number(t?.[k]||0),0)))}
function metrics(){const sales=(db()?.sales||[]).filter(s=>s.status!=='Cancelado'&&(!(s.tours||[]).length||(s.tours||[]).some(active))),clients=new Set();sales.forEach(s=>{const p=digits(s.phone),n=norm(s.name);clients.add(p.length>=8?'p:'+p:n?'n:'+n:'id:'+s.id)});const passengers=sales.reduce((a,s)=>a+pax(s),0),experiences=sales.reduce((a,s)=>a+(s.tours||[]).filter(active).length,0),commission=sales.reduce((a,s)=>{try{return a+(window.calcSaleCommission?Math.round(Number(window.calcSaleCommission(s)?.total||0)*100):Number(s.commissionCents||0))}catch(_){return a+Number(s.commissionCents||0)}},0);return{clients:clients.size,passengers,experiences,commission}}
function style(){if(document.getElementById('isaImpactStyles'))return;const s=document.createElement('style');s.id='isaImpactStyles';s.textContent='.isa-impact{margin:0 0 18px;background:linear-gradient(135deg,#0b2136,#174565);color:#fff;border-radius:19px;padding:20px;box-shadow:var(--shadow);position:relative;overflow:hidden}.isa-impact:after{content:"";position:absolute;width:190px;height:190px;border-radius:50%;right:-70px;top:-90px;background:rgba(223,168,47,.13)}.isa-impact>*{position:relative;z-index:1}.isa-impact-k{font-size:11px;text-transform:uppercase;letter-spacing:.12em;font-weight:900;color:#f4c94f}.isa-impact h2{font-size:21px;margin:6px 0 3px}.isa-impact p{margin:0;color:#d6e1e9;font-size:12px}.isa-impact-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:16px}.isa-impact-item{background:rgba(255,255,255,.1);border:1px solid rgba(255,255,255,.14);border-radius:13px;padding:12px}.isa-impact-item small{display:block;color:#c9d6df;font-size:10px}.isa-impact-item strong{display:block;margin-top:5px;font-size:21px}.isa-impact-note{margin-top:13px;font-size:12px;color:#fff3c4;font-weight:700}@media(max-width:850px){.isa-impact-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){.isa-impact-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function render(){style();const f=document.getElementById('financeiro'),g=f?.querySelector('.financegrid');if(!g)return;let b=document.getElementById('isaImpactPanel');if(!b){b=document.createElement('div');b.id='isaImpactPanel';b.className='isa-impact';g.before(b)}const m=metrics(),money=window.fmtMoney?window.fmtMoney(m.commission):new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(m.commission/100);b.innerHTML='<div class="isa-impact-k">✨ Seu impacto até aqui</div><h2>Mais do que vendas: experiências construídas</h2><p>Um retrato acumulado de tudo o que já passou pelo seu ISA.</p><div class="isa-impact-grid"><div class="isa-impact-item"><small>Clientes atendidos</small><strong>'+m.clients+'</strong></div><div class="isa-impact-item"><small>Passageiros atendidos</small><strong>'+m.passengers+'</strong></div><div class="isa-impact-item"><small>Experiências organizadas</small><strong>'+m.experiences+'</strong></div><div class="isa-impact-item"><small>Comissão acumulada</small><strong>'+money+'</strong></div></div><div class="isa-impact-note">'+(m.passengers?'Você já ajudou '+m.passengers+' '+(m.passengers===1?'pessoa':'pessoas')+' a transformar uma viagem em experiência. ✨':'Cada atendimento bem feito é o começo de uma experiência inesquecível. ✨')+'</div>'}
function install(){render();if(typeof window.renderFinance==='function'&&!window.renderFinance.__impact){const o=window.renderFinance,w=function(...a){const r=o.apply(this,a);setTimeout(render,0);return r};w.__impact=true;window.renderFinance=w}if(typeof window.renderAll==='function'&&!window.renderAll.__impact){const o=window.renderAll,w=function(...a){const r=o.apply(this,a);setTimeout(render,0);return r};w.__impact=true;window.renderAll=w}document.querySelectorAll('[data-view="financeiro"]').forEach(b=>{if(!b.__impact){b.__impact=true;b.addEventListener('click',()=>setTimeout(render,80))}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{install();[400,1300,2600].forEach(x=>setTimeout(install,x))});else{install();[400,1300,2600].forEach(x=>setTimeout(install,x))}
})();