(()=>{
'use strict';
const T=[
['Descoberta','Pergunte antes de recomendar','Entenda primeiro o que o cliente quer sentir: neve, vinho, aventura, descanso ou fotos.','Faça uma pergunta de preferência antes de sugerir um passeio.'],
['Valor','Venda o resultado, não a lista de itens','Roteiro e duração explicam o produto. O que convence é a experiência que aquilo entrega.','Traduza uma característica em benefício para o cliente.'],
['Objeções','“Está caro” ainda não é um não','Muitas vezes significa “ainda não entendi por que vale isso”. Descubra a comparação antes do desconto.','Pergunte o que ele está comparando para orientar melhor.'],
['Follow-up','Retome o benefício','Follow-up funciona melhor quando relembra o motivo da compra, e não quando vira apenas cobrança.','Leve um benefício ou informação nova no próximo retorno.'],
['WhatsApp','Uma mensagem, uma decisão','Textos longos escondem a ação principal. Contexto curto e próximo passo claro ajudam a avançar.','Revise sua próxima mensagem e destaque uma única ação.'],
['NPS','Expectativa bem alinhada melhora a experiência','Horário, ponto de encontro, roupa e o que levar parecem detalhes — até virarem dúvida.','Antecipe uma dúvida operacional antes que ela vire ansiedade.'],
['Pós-venda','O atendimento continua depois do pagamento','Uma orientação clara antes do passeio pode valer tanto quanto a venda na percepção do cliente.','Confira se quem viaja amanhã recebeu tudo o que precisa.'],
['Prova social','Use exemplos reais sem exagerar','Prova social é mais forte quando é específica e parecida com o perfil de quem está comprando.','Conte um caso curto de cliente parecido, quando fizer sentido.'],
['Urgência','Urgência boa é urgência verdadeira','Prazo, disponibilidade e condição real ajudam a decidir. Pressão inventada destrói confiança.','Se houver limite real, diga exatamente qual é e por quê.'],
['Fechamento','Facilite o próximo passo','Quanto menos esforço existir entre a decisão e a reserva, menor a chance de o cliente esfriar.','Ao perceber intenção, envie o caminho de fechamento já organizado.'],
['Escuta','Repita o que você entendeu','Resumir a necessidade mostra atenção e reduz recomendações erradas.','Use “Então, pelo que entendi, vocês procuram…” antes da oferta.'],
['Confiança','Dizer “não sei” pode vender mais','Assumir uma dúvida e confirmar depois transmite mais segurança do que improvisar.','Troque o chute por “Vou confirmar isso para você agora”.'],
['Cross-sell','Complemento bom resolve a próxima necessidade','Cross-sell não é empilhar passeios; é perceber o que falta para a viagem ficar completa.','Pergunte o que o cliente já planejou antes de sugerir algo a mais.'],
['Upsell','Mostre a diferença, não só o preço maior','Upgrade só faz sentido quando o cliente entende o ganho em conforto, tempo ou experiência.','Compare opções usando diferenças que importam para aquele cliente.'],
['Preço','Apresente valor antes do número','Quando o preço chega antes da percepção de valor, ele vira a única referência da conversa.','Explique primeiro o que está incluído e por que faz sentido.'],
['Ancoragem','Comparar opções ajuda a decidir','Duas ou três alternativas bem diferentes dão referência de valor e evitam escolha no escuro.','Mostre para quem cada opção faz mais sentido.'],
['Fechamento','Pergunte pela decisão de forma natural','Depois de esclarecer necessidade, valor e dúvidas, não deixe a conversa terminar sem próximo passo.','Pergunte: “Qual dessas opções combina mais com vocês?”'],
['Relacionamento','Use o nome do cliente com naturalidade','Personalização aproxima quando parece conversa, não roteiro decorado.','Use o nome em um ponto importante da conversa, sem repetir demais.'],
['WhatsApp','Áudio é recurso, não obrigação','Áudio aproxima, mas dificulta consulta rápida. Informações críticas ficam melhores também por escrito.','Se mandar áudio, deixe horário, valor ou endereço em texto.'],
['Objetividade','Organize a oferta visualmente','No WhatsApp, blocos curtos e poucos destaques ajudam o cliente a comparar sem se perder.','Use título, três benefícios e valor; aprofunde se ele pedir.'],
['Empatia','O contexto muda a melhor oferta','Casal, família, idosos e amigos podem querer o mesmo destino por motivos diferentes.','Pergunte quem viaja e como seria um dia perfeito para esse grupo.'],
['Objeções','Não lute contra a objeção','Primeiro valide a preocupação; depois esclareça o motivo real.','Comece por “Entendo seu ponto” antes de responder.'],
['Indicação','Cliente satisfeito pode abrir a próxima venda','O melhor momento para pedir indicação é depois de uma experiência positiva.','Após um elogio, agradeça e convide a indicar alguém.'],
['NPS','Feedback ruim é dado operacional','Uma nota baixa aponta onde a experiência quebrou; não serve só para medir satisfação.','Procure o ponto do processo que pode ser corrigido.'],
['Prioridade','Nem todo lead precisa da mesma energia','Intenção, data da viagem e nível de decisão ajudam a escolher quem merece retorno primeiro.','Priorize quem tem viagem próxima e intenção clara.'],
['Diagnóstico','Perguntas abertas revelam mais','“Você gosta de vinho?” fecha a resposta. “Que experiência vocês imaginam?” abre possibilidades.','Transforme uma pergunta de sim/não em pergunta aberta.'],
['Reciprocidade','Ajude antes de pedir a decisão','Uma orientação genuinamente útil aumenta confiança e torna o fechamento consequência do atendimento.','Entregue uma informação útil mesmo antes da compra.'],
['Segurança','Clareza vende','Quando o cliente entende o que acontece antes, durante e depois, o risco percebido diminui.','Explique o fluxo da reserva em linguagem simples.'],
['Personalização','Não recomende o “mais vendido” para todo mundo','Popularidade ajuda, mas adequação fecha melhor e gera menos arrependimento.','Explique por que a recomendação combina com aquele cliente.'],
['Preço','Desconto não corrige falta de confiança','Se a dúvida é segurança, logística ou qualidade, baixar preço não resolve a causa.','Descubra qual é a trava antes de mexer no valor.'],
['Confiança','Prometa só o que a operação controla','Uma venda ótima hoje não compensa uma expectativa impossível amanhã.','Contextualize o que depende de clima, trânsito ou terceiros.'],
['Organização','Registrar agora economiza depois','Informação guardada enquanto está fresca evita busca em conversa, retrabalho e erro.','Antes de encerrar, confira se os dados essenciais ficaram no ISA.'],
['Venda consultiva','Recomendação forte tem um “porque”','Dizer “esse é ótimo” é opinião. Dizer por que combina com o cliente é consultoria.','Complete sua indicação com “Eu te recomendo esse porque…”'],
['Fechamento','Silêncio também faz parte da venda','Depois de uma proposta clara, dê espaço para o cliente pensar e responder.','Evite mandar várias mensagens seguidas para preencher o silêncio.'],
['Fidelização','A próxima venda começa na entrega atual','Uma experiência bem acompanhada aumenta a chance de retorno, avaliação positiva e indicação.','Pense no pós-venda como parte do funil, não como tarefa final.']
];
const day=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')},uk=()=>String(window.ISA_USER?.id||window.ISA_USER?.email||'seller').replace(/[^a-z0-9_-]/gi,'_'),hash=s=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
function ready(){const a=document.querySelector('.auth-screen');if(!a)return true;const s=getComputedStyle(a);return s.display==='none'||s.visibility==='hidden'||Number(s.opacity)===0}
function show(){if(String(window.ISA_ROLE||'seller').toLowerCase()==='admin'||!ready()||document.getElementById('isaDailyInsight'))return;const k='isa_daily_insight_seen_'+uk(),d=day();if(localStorage.getItem(k)===d)return;let o=0,t=T[hash(d+'|'+uk())%T.length],x=document.createElement('div');x.id='isaDailyInsight';x.innerHTML='<style>#isaDailyInsight{position:fixed;inset:0;z-index:11950;background:rgba(4,15,27,.48);display:flex;align-items:center;justify-content:center;padding:18px;opacity:0;transition:.18s;font-family:Inter,Segoe UI,Arial,sans-serif}#isaDailyInsight.open{opacity:1}.di-card{width:min(500px,100%);background:#fff;border-radius:22px;box-shadow:0 30px 90px rgba(0,0,0,.26);overflow:hidden;transform:translateY(12px);transition:.18s}#isaDailyInsight.open .di-card{transform:none}.di-head{background:linear-gradient(135deg,#0b2136,#194a6c);color:#fff;padding:22px}.di-k{font-size:11px;text-transform:uppercase;letter-spacing:.12em;color:#f4c94f;font-weight:900}.di-head h2{font-size:23px;margin:7px 0 3px}.di-head p{margin:0;color:#cbd8e2;font-size:12px}.di-body{padding:21px 22px}.di-cat{display:inline-flex;background:#fff3cc;color:#8a5c00;border-radius:999px;padding:5px 9px;font-size:10px;font-weight:900;margin-bottom:11px}.di-title{font-size:19px;font-weight:900;color:#142538;margin-bottom:8px}.di-text{font-size:14px;line-height:1.55;color:#425166}.di-action{margin-top:14px;padding:12px 13px;background:#f5f8fb;border:1px solid #e1e8ef;border-radius:12px;font-size:12px;line-height:1.5;color:#293a4d}.di-actions{display:flex;gap:8px;justify-content:flex-end;margin-top:18px}.di-btn{border:0;border-radius:11px;padding:10px 14px;font-weight:900;cursor:pointer}.di-alt{background:#edf2f7;color:#0b2136}.di-ok{background:#dfa82f;color:#0b2136}</style><div class="di-card"><div class="di-head"><div class="di-k">💡 Insight do dia</div><h2>Uma ideia para vender melhor</h2><p>Curto, prático e feito para usar no atendimento de hoje.</p></div><div class="di-body"><div class="di-cat"></div><div class="di-title"></div><div class="di-text"></div><div class="di-action"></div><div class="di-actions"><button class="di-btn di-alt">Outra dica</button><button class="di-btn di-ok">Entendi</button></div></div></div>';
const paint=()=>{x.querySelector('.di-cat').textContent=t[0];x.querySelector('.di-title').textContent=t[1];x.querySelector('.di-text').textContent=t[2];x.querySelector('.di-action').innerHTML='<strong>Experimente hoje:</strong> '+t[3]},close=()=>{localStorage.setItem(k,d);x.classList.remove('open');setTimeout(()=>x.remove(),180)};x.querySelector('.di-alt').onclick=()=>{o++;t=T[(hash(d+'|'+uk())+o)%T.length];paint()};x.querySelector('.di-ok').onclick=close;x.onclick=e=>{if(e.target===x)close()};paint();document.body.appendChild(x);requestAnimationFrame(()=>x.classList.add('open'))}
function boot(){let n=0;(function wait(){if(!ready()||document.getElementById('isaReleaseNotes')){if(n++<240)setTimeout(wait,700);return}setTimeout(show,2200)})()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,900));else setTimeout(boot,900);
})();